function zodiac() {
  let birthmonth = document.getElementById("month").value;
  let birthday = document.getElementById("day").value;
  let result = " Please enter a valid date";


  if (birthmonth == 1 && birthday >= 20 || birthmonth == 2 && birthday <= 18) {
    result = ("Aquarius");
    document.getElementById("photo").innerHTML="<img src='https://www.thesun.co.uk/wp-content/uploads/2019/09/NINTCHDBPICT000596530379.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "2021 is the year to be an Aquarius! It is all about your ever-evolving sign that presents a unique and accepting perspective to the world at large. You are here to really provide inspiration to the planet as everyone around you seems to be super confused about where to turn next.<br> <br> Your Water-bearing sign is ready to embrace and fully appreciate the amazing vibration gifts the universe has in store! It is truly a time to ask your spirit guides for what you want, and find a surprise waiting for you around every corner! <br> <br>As Saturn briefly entered your sign in 2020 experiencing a six-month retrograde cycle, you've gotten an idea of where you are headed this year. The structured planet is now transiting through your eccentric sign that enjoys the unknown twists and turns that bring forward many surprises and adventures. <br> <br>The year is marked by some intense squares between Saturn in your sign and Uranus in the fellow fixed sign of Taurus. Because you are co-ruled by both of these two outer-bodies, this is going to be an exponential lesson for you. <br> <br>There is a strong connection to time itself these days. You might feel throughout the year that time is either moving extremely fast or slowed down to a glacial pace. The most pointed squares being present on February 14, June 14, and December 24 will really test your sense of time in general. The entire purpose of this energy is to align you with your spiritual awareness and allow you to make decisions from your sense of intuitive awareness.<br> <br><br> <br>";
  }

  if (birthmonth == 2 && birthday >= 19 && birthday <=29 || birthmonth == 3 && birthday <= 20) {
    result = ("Pisces");
    document.getElementById("photo").innerHTML="<img src='https://cf.ltkcdn.net/horoscopes/images/std/259307-425x274-pisces-glyph.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "There's a difficult energy to pin down this year, Pisces. You have to really take the approach of allowing life to come as it is for your sensitive sign of the Fish. <br> <br>The most pivotal transit affecting your chart includes a series of eclipses between Gemini and Sagittarius that activate your personal tenth and fourth houses. These are more specifically your zones of career pursuits and family development. Whenever you feel like you are getting out-of-control this year, one strategy to take that will really help you is to always follow your grounded path. <br> <br>As Uranus continues to break boundaries in Taurus, this outer planet is also met with a conflicting square with Saturn in Aquarius. This holds the element of extremes, especially in mid-February, mid-June, and late December; but sparks certain events that also affect your loving sign throughout the entirety of the year. <br> <br>Yes, this energy will challenge you on many levels, especially through your personal realms of communication and psychic development. For those Pisces who are open to their gifts, this will be extremely easy for you, and for those who have suppressed your personal intuitive nature, this can feel a little overwhelming at times. <br> <br>You are extremely in tune with the unseen world this year, and it can feel like you're able to predict things before they even happen! It is a good year to work with others that support you, and also share your gifts as well. During this fascinating year, your spiritual life might even deepen.<br> <br><br> <br>";

  }
  if (birthmonth == 3 && birthday >= 21 || birthmonth == 4 && birthday <= 19) {
    result = ("Aries");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/aries-zodiac-sign-abstract-night-sky-background-royalty-free-image-1584536731.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "There is a great deal to be learned through the other side of the story these days, Aries. 2020 brought out your more practical and protective side. You were forced to dive so deeply inward, and now you know what you are able to take, and what you can no longer tolerate in your life. <br> <br>As you pummel into 2021 with your naturally inquisitive nature, there can be an honest review of where you want to direct the show. This means that you must take authority back in some capacity throughout the year. <br> <br>Saturn's influence in Aquarius sextiles your sign nicely, giving you a boost of confidence in your career pursuits. This energy can even help you heal some issues around respect and open your mind to new and different methods of leadership. This holds true for you even when a square formed between Saturn in the Water-bearing sign and Uranus in your neighboring sign of Taurus on February 17, June 14, and December 24. There's a direct emphasis on your self-worth during these months as you become more aware of what is best for the greater good. <br> <br>You might feel torn at times if you are striving hard and finding strength by following your own direction. If you keep your eye on the prize, you will not leave anyone behind. In fact, you are carving a lesser-known path to lead the way for an entire community. This year, certain lunar eclipses vacillate between Sagittarius and Gemini, activating your personal zones of higher learning and spiritual development, and requiring you to find the words for what you are feeling. <br> <br>In 2021, you might have many moments of precognition or feel more in alignment with your intuition, especially surrounding the Sagittarian eclipses, being a May 26 total lunar eclipse and a total solar eclipse on December 4.<br> <br><br> <br>";
  }

  if (birthmonth == 4 && birthday >= 20 && birthday <=30 || birthmonth == 5 && birthday <= 20) {
    result = ("Taurus");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/taurus-zodiac-sign-abstract-night-sky-background-royalty-free-image-1587395874.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "Welcome to a brand-new year ahead of you, Taurus! There's a ton of unpacking you have yet to do, and yet you do not even know where to fully begin. You've been experiencing the lessons of having the planet of chaos charging through your sign with both glimpses in 2018 and moving full-on in 2019. However, this year adds a bit of strife to this energy.<br> <br> Uranus does not like constraints under any circumstances, and as Saturn opens the year strongly situated in fellow fixed sign Aquarius, you could find yourself in a continual crossroads. In fact, this is the overall energy of your year. Feeling like you are moving forward and being yanked into place having to wait for changes to take their full effect. You might see through things so much that at times, it might even anger you. This year requires a great deal of maturity and patience on your part. Yes, there can feel like great losses, mainly not through your own undoing, but through the continual clash between Saturn in the Water-bearing Aquarius and outer-body Uranus in your sign. <br> <br>The year's lunar cycles are eye-opening in your personal zones of self-acceptance and spiritual growth. The May 26 total lunar eclipse in Sagittarius does shed light on those areas of your life that you've tried to sweep under the rug. Understand that eclipses are galvanizing energy that truly wants you to get real with yourself so that you may heal from this situation. The annual solar eclipse in Gemini on June 10 can add some clarity to your overall financial destiny—also reflected with a partial lunar eclipse in your sign of the Bull on November 19. Then luckily, you'll feel the weight off your shoulders on December 4 as the total solar eclipse sees you revisiting certain events and scenarios around your karmic connections, this time with a renewed sense of self.<br> <br><br> <br>";

  }

  if (birthmonth == 5 && birthday >= 21 || birthmonth == 6 && birthday <= 20) {
    result = ("Gemini");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gemini-zodiac-sign-abstract-night-sky-background-royalty-free-image-1590508367.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "There’s for sure plenty to talk about this year, Gemini! 2021 is a highly stimulating year for your creative sign. You are able to feel more aligned with your highest good, and can even make some pretty fantastic new friends along the way. You might actually be the go-to person when things get a little rocky, mainly because you adjust so easily and quickly to things and are able to see the humor in almost any situation. <br> <br>As the year begins with some confrontational squares between Jupiter in Aquarius and Uranus in Taurus, you'll get a beneficial wave of abundance headed your way even through some gritty energy. This is also true in mid-February, May, and late December for you as Saturn's transit through Aquarius squares Uranus in Taurus, causing some chaotic waves in the world.<br> <br> This can be tough on others through much of the year; but because Saturn will be nicely angled towards your airy sign, it will be bringing you many insights and brilliant moments. This can be that time where you find yourself in a very powerful way. Expect the unexpected and be extremely grateful for the gifts you receive, because you deserve them! One important piece of the 2021 puzzle is to really consider the transition period of your birthday months. You might be a little caught up during this year's Mercury retrograde cycles, which all take place in air signs.<br> <br> One of the most important for you occurs on May 29, following a transformative total lunar eclipse in your opposing sign of Sagittarius. This is a vibe that will definitely have you rethinking a lot of different pieces of the story. And although it can be a highly enlightening time when it comes to all aspects of your life, there is still much work to be done through the summer. Especially because you are also met with an annular solar eclipse on June 10—at the same time Mercury continues a tricky retrograde cycle in your sign until June 22.<br> <br><br> <br>";

  }

  if (birthmonth == 6 && birthday >= 21 && birthday <=30 || birthmonth == 7 && birthday <= 22) {
    result = ("Cancer");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/cancer-zodiac-sign-abstract-night-sky-background-royalty-free-image-858078918-1560803578.jpg?crop=0.66777xw:1xh;center,top&resize=480:*' width=20%>";
    document.getElementById("characteristic").innerHTML = "You are here for a major reason, and 2021 is one of those years where you've got to surrender to the outcome. You made some incredible changes during 2020 and are making some real headway. There were many ups and downs that could have felt a little more traumatic than normal, especially for your compassionate sign of the Crab. <br> <br>This year really serves as looking at your life from an outsider's perspective. You're able to take an observer’s perspective and might even consider diving into some deep self-reflection that you once shied away from. Working in several facets of spirituality, body care, research, and expanding your mind, in general, is what 2021 is all about. There is nothing too out-of-the-ordinary for you right now, as you might even be more interested in either paranormal or occult-type studies. <br> <br>You are extremely tied to the cycles of the moon, who's nodes now cycle between Gemini in the north position and Sagittarius in the south position. You are working out karmic cycles through learning your own patterns in communication and understanding what stories you've been told for far too long. You might even be faced with the truth about a family situation that you once spent far too much time trying to resolve. Maybe you've sacrificed your own happiness for the good of your loved ones only to come to terms with what you really want for yourself. <br> <br>This is a year where you can really step into your own independence and gain a little emotional space from the judgments of others. There's a refreshing tone to your life once you accept the truth about something you've been stuffing under the rug. 2021, in general, is a time for you to face the music, and see how special you really are! Stop being so hard on yourself, loving Cancer!<br> <br><br> <br>";

  }
  if (birthmonth == 7 && birthday >= 23 || birthmonth == 8 && birthday <= 22) {
    result = ("Leo");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/leo-zodiac-sign-abstract-night-sky-background-royalty-free-image-858075636-1563569425.jpg?crop=1.00xw:0.751xh;0,0.134xh&resize=1200:*' width=20%>";
    document.getElementById("characteristic").innerHTML = "This is a huge year for your exuberant sign, Leo! There is so much going on, that it is often hard to keep track of all the wonderful goodies in store for your sign of the Lion! A major component of this year is also learning how to let go and surrender to the unknown. <br> <br>The theme for your fire sign is to have the patience to know that it will all end up exactly the way it is supposed to be! Along these lines, you are met with incredible tests of faith throughout 2021 that will leave you flabbergasted at how awesome it is to be yourself! There will be some emotional tests and energetic changes, but with your commanding presence, you'll be able to handle it all with ease. <br> <br>The year begins with a strong mid-January square between Jupiter in your opposing sign of Aquarius and Uranus in fellow fixed sign Taurus, creating a challenging T-square energy in your chart. This isn't the easiest of configurations to deal with at all, requiring extreme self-care in many circumstances. <br> <br>This T-square affects all realms of your life, and is also brought around again with the Saturn in Aquarius square to Uranus in Taurus, spanning a cosmic influence through mid-February, mid-June, and late December. These will be time periods where you'll face a ton of internal and external friction, and in many cases, can be a certain straw that breaks the camel’s back with respect to your career, relationships, and public life. <br> <br>Finally, this year’s lunar eclipses will also trigger some important cycles highlighting your personal zones of self-expression, professional relationships, and community development in May, June, November, and December.<br> <br><br> <br>";

  }
  if (birthmonth == 8 && birthday >= 23 || birthmonth == 9 && birthday <= 22) {
    result = ("Virgo");
    document.getElementById("photo").innerHTML="<img src='https://i.postimg.cc/MGZWtTf8/28504630-shutterstock-728321317-1.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "This is a major career year for your sign, Virgo. Your analytical self will enjoy the hard work and dedication it takes to make your dreams become a reality, but you also get a little boost of love from the cosmic cycles as well. You've done a lot of good deeds for so many people that it's kind of your time to let some good be returned to you as well. The only problem is sitting still and letting yourself have some fun along the way! <br> <br>A major aspect this year is your tenth house and fourth house being influenced by the current nodal transits as well as the lunar eclipses. The moon’s north node of fate transits through Gemini and sits high in your zone of career development, asking you to enjoy life a little more even as you are often obsessed with staying in control. The south node in Sagittarius asks you to let go of what no longer serves your soul and wants you to let go of any false narratives that have held you back. <br> <br>More specifically, your energy is tied to the May 26 total lunar eclipse, the June 10 annular solar eclipse, the November 19 partial lunar eclipse, and the December 4 total solar eclipse. These dates can help you set a schedule and look at the actual patterns unfolding in your life at these specific times. You're going to be challenged to the max, but you will find your way through your own destined path. Your earthy sign is being given a lot of chances to prove yourself this year, as you are meant to fully thrive in all realms of life, love, and business.<br> <br><br> <br>";
  }
  if (birthmonth == 9 && birthday >= 23 && birthday <=30 || birthmonth == 10 && birthday <= 22) {
    result = ("Libra");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/libra-zodiac-sign-abstract-night-sky-background-royalty-free-image-1568910403.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "Wow, what a year you truly have in store for yourself, Libra! 2021 emphasizes your true gift of communication bringing out the more creative qualities of your sign. You might even consider focusing your attention on your more artistic and altruistic forms of expression. As an air sign, you find yourself on a quest for knowledge and might even consider entering a program of study that expands your understanding of various subjects. <br> <br>The north node's transit through Gemini directs your personal magnetism towards continued education, spiritual expansion, and even connects you to communities around the world. You might even consider directing your energy towards more humanitarian causes as Saturn's presence in Aquarius trines your sign and connects you to several causes that you feel most passionate about. You are a sign that seeks diplomacy and justice, which you know does not happen overnight. You are willing to put in the time and effort to really see certain things through and know that this is a full-year process ahead. You might even consider volunteering your time with certain organizations, and find yourself continually inspired by the stories of others as you deepen your understanding and research within your community. <br> <br>A very enlightening lesson this year includes the cycles of Mercury retrograde, which are all in air signs. This begins with an Aquarian retrograde during the months of January and February, creating an editing period for your fifth house, affecting your children and creative talents. As Mercury retrograde asks us all to investigate things more deeply, this is also an important lesson for all your relationships. <br> <br>You'll feel more challenged by a Gemini retrograde cycle from May through early July. This can be a bit tricky in your communication style, and bring unwanted confusion. The year also brings a healing Mercury retrograde in your sign of the Scales from late September through mid-November. <br> <br>In general, there's a lot of activity in the second half of the year in terms of questions and resolutions involving love.<br> <br><br> <br>";
  }
  if (birthmonth == 10 && birthday >= 23 || birthmonth == 11 && birthday <= 21) {
    result = ("Scorpio");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/scorpio-zodiac-sign-abstract-night-sky-background-royalty-free-image-1571399986.jpg?crop=1.00xw:0.751xh;0,0.120xh&resize=1200:*' width=20%>";
    document.getElementById("characteristic").innerHTML = "This is an extremely important year for your powerful sign of the Scorpion. Several transits tug and pull at major points in your personal chart, bringing you brand-new perspectives, and also requiring you to implement decisions that contribute to both, your family and career life.<br> <br> This combines several areas of your personal affairs and asks you to really look into your long-term arrangements from the perspective of a leader, caretaker, and healer. As 2021 brings along with it an influential square between Saturn in Aquarius and Uranus in your opposing sign of Taurus, this creates a prominent T-square in your own chart. This can be a difficult astrological energy most pointedly experienced during mid-February, mid-June, and the end of December, but leads to radical change in your overall life. There can be many unplanned events that ultimately decide your fate and affect your home and career situations. You might even consider moving for work, or relocating in some capacity. <br> <br>Pluto, your home planet, enters a retrograde cycle through Capricorn between June 28 and October 7, making this timeframe a key zone to revisit what still needs to be accomplished in order to feel fully empowered and take back your personal authority in certain areas where you felt you lost your confidence. Some see you from the outside that have no idea what's been bubbling under the surface. Don’t lose sight of the big picture, and always remember that the universe wants you to succeed at anything you set your mind to, and this year is no exception to that rule.<br> <br><br> <br>";
  }
  if (birthmonth == 11 && birthday >= 22 && birthday <=30 || birthmonth == 12 && birthday <= 21) {
    result = ("Sagittarius");
    document.getElementById("photo").innerHTML="<img src='https://media.istockphoto.com/photos/sagittarius-zodiac-sign-abstract-night-sky-background-picture-id858080490?k=6&m=858080490&s=612x612&w=0&h=1MwRkJYG0XQQ75U-rMITlrjdd7DIvh1Q02YO--dRkxo=' width=20%>";
    document.getElementById("characteristic").innerHTML = "What an absolute turning point kind of year 2021 will be for you, Sagittarius! There is a miraculous energy all around you that is quite refreshing for your benevolent sign of the Centaur. You will have times of massive self-reflection that can trigger old wounds, also met by extremely gracious moments of friendship! <br> <br>The presence of the lunar and solar eclipses cycle through both, your personal sign and opposing realm of the Twins. This helps you get a full perspective and observe the world through a brand-new scope. You have various mass realizations this year that will set you on a successful course. <br> <br>The May 26 total lunar eclipse in your sign, for example, provides a massive release in your personal life that is both purifying and strengthening. This can be an energetic blockage you've had for years that lifts and releases from your life. You may feel more exposed than normal, but that is the point of these shifts. Later on, as an illuminating annular solar eclipse in Gemini galvanizes your personal seventh house of partnerships on June 10, there is no place to hide! You are out and proud of whatever you believe in! <br> <br>The goal this year is to get you expressing from a more heartfelt space. Appreciating life, and living it up is what it's all about these days. Even with the hardships of the world, your Jupiterian sign can really feel the love even through the tougher of times. The year concludes with a total solar eclipse in your sign on December 4, igniting your passions and bringing fruitful messages from the cosmic forces that be!<br> <br><br> <br>";
  }

  if (birthmonth == 12 && birthday >= 22 || birthmonth == 1 && birthday <= 19) {
    result = ("Capricorn");
    document.getElementById("photo").innerHTML="<img src='https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/capricorn-zodiac-sign-abstract-night-sky-background-royalty-free-image-1576705058.jpg' width=20%>";
    document.getElementById("characteristic").innerHTML = "You have woken up to a different version of yourself this year, Capricorn! You are a unique soul that is here for a welcoming purpose on this earth! The presence of your home planet Saturn through the sign of Aquarius is in full force this year, and has many lessons for your sign of the Goat to take in and process. <br> <br>There is some element of psychology pulling at you, which requires you to be wise beyond your years. You are experiencing a new world for yourself, and might even long for things to go back to the way they were. But the innovative influence of Aquarius will have you feeling more emotionally detached from your partnerships and friendships, pulling you into the future! <br> <br>As a sign who often puts work over love, this can be a little easier for those Goats who just want some energy to jump into their professional life with zero constraints. For those who are ignoring your relationship duties because work gets in the way, this is a year where you can truly come face-to-face in this respect, and be open about your feelings. <br> <br>There is some pattern that needs to be reassessed in your overall life. The difficult square between Saturn in Aquarius and Uranus in Taurus takes you away from the original structure you once perceived to be the rules, and now asks you to be a little more radical and step out of your own way. The turning points this year are not limited to mid-February, mid-June, and late December, but do bring on these squares in strong. This is a lesson that will test your self-esteem, but that is meant to cleanse your second chakra of creativity.<br> <br><br> <br>";
  }

  if (birthmonth > 12 || birthday > 31) {
    result = ("Not Applicable")
    document.getElementById("photo").innerHTML="<img src='' width=20%>";
    document.getElementById("characteristic").innerHTML = "Please enter a correct date."
  }
  document.getElementById("output").innerHTML = result;
}
